### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by anranyicheng** [crategus/cl-cffi-gtk4#1]
Nice to see a new version of the library, do you have any plans to use the MIT license for this new project?

**Comment by crategus** [comment]
I didn't give much thought to the type of license. The MIT license is more liberal. For me it is fine. The cl-cffi-gtk4 library uses code from 2010 by Kalyanov Dmitry. There is no license agreed in the public repository https://github.com/dmitryvk/cl-gtk2 for the code. So I think I will specify the MIT license for this library and for the other libraries that cl-cffi-gtk4 requires.

**Comment by anranyicheng** [comment]
I am very glad to see you release your own license. I believe this software library will benefit more people and be used more widely. Thanks
